### ISSUE TITLE
External FHIRpath service

### ISSUE THREAD

**Issue by jhlee-mitre** [fhir-crucible/testscript-engine#51]
**Goal**
Implement function to handle wherever FHIR path support needed in TestScript

**FHIR Spec**
https://www.hl7.org/fhir/testscript-definitions.html#TestScript.variable.expression
https://www.hl7.org/fhir/testscript-definitions.html#TestScript.setup.action.assert.compareToSourceExpression
https://www.hl7.org/fhir/testscript-definitions.html#TestScript.setup.action.assert.expression

**Method**
Connect external FHIR Path service in addition to native Ruby FHIR path
https://www.rubydoc.info/gems/fhir_models/4.1.2/FHIRPath

Place to implement
evaluate_expression()
compareToSourceExpression()

**Comment by karlnaden** [comment]
# External FHIR Path Support design

## Overview
Testing in FHIR often involves inspection of specific details of returned FHIR resources. FHIR Path is the format-agnostic language for pulling specific values out of a FHIR resource and several elements within TestScript support the provision of a FHIR Path expression, including in assertions and variable definitions. The Ruby-based FHIR Crucible implementation of FHIR path covers the basics, but does not support FHIR Path in full.  Several external tools do include more robust implementations of FHIR Path and other users/contributors to the FHIR Crucible project have decided to use those external engines rather than investing further in the FHIR Crucible implementation. While the TestScript-engine may be run in contexts where external tools are not available and so need to use the FHIR Crucible implementation, implementing optional support for an external FHIR path engine will allow further TestScript experimentation and potentially help to guide targeted improvements to the FHIR Crucible FHIR Path implementation.

## Requirements

1. Support for FHIR Path evaluation using the FHIR Crucible implementation
2. Support for FHIR Path evaluation using an external FHIR Path engine
3. Command-line configuration options to be able to decide which to use

## Proposed Approach

We propose to implement support for a single external FHIR Path implementation to allow for this experimentation with TestScripts not yet supported by the FHIR Crucible FHIR Path implementation. Specifically, we will use the Inferno [fhir-validator-wrapper](https://github.com/inferno-framework/fhir-validator-wrapper) project which includes a [FHIR Path evaluation API](https://github.com/inferno-framework/fhir-validator-wrapper/blob/master/rest-api.md#fhirpath-routes).

- Default = use internal FHIR Crucible FHIR Path implementation
- Options
  - useExternalFHIRPathEngine flag -> defaults to False. If true external FHIRPath evaluation will be used
  - ExternalFHIRPathEngineURL -> used only if useExternalFHIRPathEngine is True. defaults to the ONC Inferno public instance if not set and useExternalFHIRPathEngine is True. Used to direct to an alternate location, such as a local copy. Requests sent to [ExternalFHIRPathEngineURL]/[evaluate](https://github.com/inferno-framework/fhir-validator-wrapper/blob/master/rest-api.md#evaluate-a-fhirpath-expression).

## Example TestScripts
- https://github.com/fhir-crucible/testscript-engine/blob/mCODE/TestScripts/TestScript-us-mcode-profile-search-comorbidities.json - setup.action[1].assert.expression
- https://github.com/fhir-crucible/testscript-engine/blob/mCODE/TestScripts/TestScript-us-mcode-identify-cancer-patients-by-group.json - variable[0].expression
